Upgrade cpuinfo to be compatible with tensorflow r2.15 (#2)
upgrade to git_tag: ef634603954d88d2643d5809011288b890ac126e
fix link issue: undefined reference to `cpuinfo_has_x86_avxvnni'

Co-authored-by: Xiaomei Shang <xiaomei.shang@synaptics.com>